Refactor deployment workflows and improve validation
Renamed the deploy_web job to deploy_web_dev in the cloud-deploy-web.yml workflow. In the cloud-deploy.yml, removed outdated code and added a new check output values step to verify output values before starting the deployment notification. This additional validation aims to ensure that all necessary environment variables are correctly set before proceeding with the deployment.

diff --git a/.github/workflows/cloud-deploy.yml b/.github/workflows/cloud-deploy.yml
--- a/.github/workflows/cloud-deploy.yml
+++ b/.github/workflows/cloud-deploy.yml
@@ -38,7 +38,17 @@ jobs:
             envvalue="prod"
           fi
           echo "environvalue=$envvalue" >> $GITHUB_ENV  
-      
+
+      - name: Check output values
+        run: |
+          echo "Environment Name: ${{ steps.env_name.outputs.env_Name }}"
+          echo "Environment Value: ${{ steps.setenv.outputs.envvalue }}"
+          if [ -z "${{ steps.env_name.outputs.env_Name }}" ] || [ -z "${{ steps.setenv.outputs.envvalue }}" ]; then
+            echo "One of the required output values has not been set. Failing..."
+            exit 1
+          else
+            echo "All output values have been set successfully."
+          fi
 
       - name: Start Deployment Notification
         uses: ravsamhq/notify-slack-action@v2
