feat(ci): A new approach without tagging of a git repository during WF running

diff --git a/.github/workflows/community-releases.yml b/.github/workflows/community-releases.yml
--- a/.github/workflows/community-releases.yml
+++ b/.github/workflows/community-releases.yml
@@ -1,7 +1,9 @@
 name: Prepare Self-hosted Release
 
 on:
-  workflow_dispatch:
+  push:
+    tags:
+      - 'v[0-9]+.[0-9]+.[0-9]+'
 
 permissions:
   contents: write
@@ -22,26 +24,15 @@ jobs:
         id: get_version
         shell: bash
         run: |
-          echo "latest-version=$(jq -r '.version' lerna.json)" >> $GITHUB_OUTPUT
-
-      - name: Check if tag already exists
-        id: check_tag
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const { data: tags } = await github.rest.git.listMatchingRefs({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              ref: 'tags/v${{ steps.get_version.outputs.latest-version }}'
-            });
-            const tagExists = tags.length > 0;
-            console.log(`Tag exists: ${tagExists}`);
-            return tagExists;
-
-      - name: The v${{ steps.get_version.outputs.latest-version }} tag already exists
-        if: steps.check_tag.outputs.result == 'true'
-        run: |
-          echo "::notice::The v${{ steps.get_version.outputs.latest-version }} tag already exists."
+          LATEST_VERSION=v$(jq -r '.version' lerna.json)
+          CURRENT_GIT_TAG=${{  github.ref_name }}
+          if ["$LATEST_VERSION" == "$CURRENT_GIT_TAG"]
+          then
+            echo "latest-version=$(jq -r '.version' lerna.json)" >> $GITHUB_OUTPUT
+          else
+            echo "::error::The version in the file lerna.json does not match the git tag. The version in lerna.json is $LATEST_VERSION. The git version is $CURRENT_GIT_TAG"
+            exit 1
+          fi
 
   build_docker:
     runs-on: ubuntu-latest
@@ -132,22 +123,3 @@ jobs:
           docker tag novu-$SERVICE_COMMON_NAME ghcr.io/$REGISTRY_OWNER/${{ matrix.name }}:latest
           docker push ghcr.io/$REGISTRY_OWNER/${{ matrix.name }}:${{ needs.prepare.outputs.latest-version }}
           docker push ghcr.io/$REGISTRY_OWNER/${{ matrix.name }}:latest
-
-  tag_create:
-    runs-on: ubuntu-latest
-    needs:
-      - prepare
-      - build_docker
-    timeout-minutes: 80
-    steps:
-      - name: Create tag v${{ needs.prepare.outputs.latest-version }} in the GIT Repo
-        if: ${{ needs.prepare.outputs.check_tag_result != 'true' }}
-        uses: actions/github-script@v7
-        with:
-          script: |
-            github.rest.git.createRef({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              ref: 'refs/tags/v${{ needs.prepare.outputs.latest-version }}',
-              sha: context.sha
-            })
