Add validation for branch names in Github action
In the "on-pr-change" Github action, additional validation checks have been added to ensure the HEAD_REF and BASE_REF branch names do not contain invalid characters. Now, the script checks for invalid characters in branch names and restricts merge requests to the prod branch only from the next branch.

diff --git a/.github/workflows/on-pr-change.yml b/.github/workflows/on-pr-change.yml
--- a/.github/workflows/on-pr-change.yml
+++ b/.github/workflows/on-pr-change.yml
@@ -11,8 +11,19 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Check branches
+        env:
+          HEAD_REF: ${{ github.head_ref }}
+          BASE_REF: ${{ github.base_ref }}
         run: |
-          if [ ${{ github.head_ref }} != "next" ] && [ ${{ github.base_ref }} == "prod" ]; then
+          if [[ "${{ env.HEAD_REF }}" =~ [^a-zA-Z0-9-_] ]]; then
+            echo "head_ref has invalid characters."
+            exit 1
+          fi
+          if [[ "${{ env.BASE_REF }}" =~ [^a-zA-Z0-9-_] ]]; then
+            echo "base_ref has invalid characters."
+            exit 1
+          fi
+          if [ ${{ env.HEAD_REF }} != "next" ] && [ ${{ env.BASE_REF }} == "prod" ]; then
             echo "Merge requests to prod branch are only allowed from next branch."
             exit 1
           fi
