feat(ci): Netlify rollback job by using a commit hash

diff --git a/.github/workflows/rollback.yml b/.github/workflows/rollback.yml
--- a/.github/workflows/rollback.yml
+++ b/.github/workflows/rollback.yml
@@ -213,6 +213,11 @@ jobs:
       NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
     steps:
       - run: echo "Rolling back ${{ github.event.inputs.service }} in ${{ github.event.inputs.environment }}"
+
+      - id: commit
+        if: contains(fromJson('["Commit Hash"]'), github.event.inputs.mode)
+        uses: prompt/actions-commit-hash@v3
+
       - name: Prepare variables
         id: variables
         run: |
@@ -240,6 +245,7 @@ jobs:
           fi
 
       - name: Get Current Deploy ID
+        if: contains(fromJson('["Previous Version"]'), github.event.inputs.mode)
         id: get_current_deploy
         env:
           NETLIFY_SITE_ID: ${{ env.netlify_site_id }}
@@ -249,12 +255,14 @@ jobs:
           echo "current_deploy_id=$current_deploy_id" >> $GITHUB_ENV
 
       - name: Find Previous Production Deployments
+        if: contains(fromJson('["Previous Version"]'), github.event.inputs.mode)
         id: find_previous_deployments
         env:
           NETLIFY_SITE_ID: ${{ env.netlify_site_id }}
         run: |
 
       - name: Find Previous Production Deployments and Determine Previous Deploy ID
+        if: contains(fromJson('["Previous Version"]'), github.event.inputs.mode)
         id: previous_deploy_id
         env:
           NETLIFY_SITE_ID: ${{ env.netlify_site_id }}
@@ -265,6 +273,22 @@ jobs:
           previous_index=$((current_index - 1))
           previous_deploy_id=$(echo "$deploy_ids" | sed "${previous_index}q;d")
           echo "previous_deploy_id=$previous_deploy_id" >> $GITHUB_ENV
+
+      - name: Determine Previous Deploy ID
+        if: env.previous_deploy_id != null && contains(fromJson('["Commit Hash"]'), github.event.inputs.mode)
+        env:
+          NETLIFY_SITE_ID: ${{ env.netlify_site_id }}
+          COMMIT_REF: ${{ steps.commit.outputs.hash }}
+        run: |
+          response=$(curl -s -H "Authorization: Bearer $NETLIFY_ACCESS_TOKEN" "https://api.netlify.com/api/v1/sites/$NETLIFY_SITE_ID/deploys")
+          deploy_id=$(echo "$response" | jq -r ".[] | select(.commit_ref == \"$COMMIT_REF\") | .id")
+          if [ -n "$deploy_id" ]; then
+              echo "Deploy ID for commit $COMMIT_REF: $deploy_id"
+              echo "previous_deploy_id=$deploy_id" >> $GITHUB_ENV
+          else
+              echo "Deploy not found for commit $COMMIT_REF"
+              exit 1
+          fi
 
       - name: Rollback to Previous Deploy
         if: env.previous_deploy_id != null
